{% set version = "1.0.25" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bbmle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bbmle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bbmle/bbmle_{{ version }}.tar.gz
  sha256: 86a8c69902fbf6caf337f9bc532afe89dc2a59dd24287a2423d781797010b255

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-lattice
    - r-numderiv
    - r-bdsmatrix
    - r-matrix
    - r-mvtnorm
  run:
    - r-base
    - r-mass
    - r-lattice
    - r-numderiv
    - r-bdsmatrix
    - r-matrix
    - r-mvtnorm

test:
  commands:
    - $R -e "library('bbmle')"           # [not win]
    - "\"%R%\" -e \"library('bbmle')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bbmle
  license: GPL-2.0-or-later
  summary: Methods and functions for fitting maximum likelihood models in R. This package modifies and extends the 'mle' classes in the 'stats4' package.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bbmle
# Title: Tools for General Maximum Likelihood Estimation
# Version: 1.0.20
# Author: Ben Bolker <bolker@mcmaster.ca>, R Development Core Team
# Maintainer: Ben Bolker <bolker@mcmaster.ca>
# Depends: R (>= 3.0.0), stats4
# Imports: stats, numDeriv, lattice, MASS, methods
# Suggests: emdbook, rms, ggplot2, RUnit, MuMIn, AICcmodavg, Hmisc, optimx (>= 2013.8.6), knitr, testthat
# VignetteBuilder: knitr
# BuildVignettes: yes
# Description: Methods and functions for fitting maximum likelihood models in R. This package modifies and extends the 'mle' classes in the 'stats4' package.
# License: GPL
# Collate: 'mle2-class.R' 'mle2-methods.R' 'mle.R' 'confint.R' 'predict.R' 'profile.R' 'update.R' 'dists.R' 'IC.R' 'slice.R'
# NeedsCompilation: no
# Packaged: 2017-10-30 02:06:08 UTC; bolker
# Repository: CRAN
# Date/Publication: 2017-10-30 08:49:56 UTC
