appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: RP7tGlFqhpSIPMOLrbBx4Eup+4TVUmrtLRSuDBIkSWq0m57nOQIf9+EXLZD+HL+SDPOdF/AeL1CDIrt2mmmYkI94z8MiJxg4bDE0yx88gRah0rHF0vrqIiIhcGDSy6hSMFGLVVA1gk92aSTSHg5j7xpfBwTDUlZ8Rnr9TV0MHoMEDDVlAg8Ce6vjfi28FFdLL8PUFoFaOm1O/RVqkxsXAoxWA64JgSWJub8vgQoLSdJPbLugBT8Rti8+JrEdmVamSMS442FLtigcE7ps7MxmDH8mw4W+EjeF04njq2AJXRtqbZtAQBcBsW5c79y+mOt7Gf2ebUJzpGhJdnNQb1mtquNtES4soU02mm9KJZRzjkbwhCDti3HmNpQsHeEMpwpMbvdJfrylxwb276cMsYJBaHRba0NrLa/Nv9rKCip+ddeFTqLJT8DKs3IwmaPW+dwZFBAQP9PTYqAFOy0BetO5iP6xbsfD/Qy4+CA5PlNblYUqmYImNuk7oWGB6s5AUc13XjybqCvVmBRlRwjTz9g4EXbt4KbbbNo9KYbasB5gP2tqHwq1qoiPasxW9hx5Kl2gYTb6U37cE2Fk/qDX74HpSfMDB/0MofrAesy5DFKtoUVdFq4VbND/+ZfMsUFhLUMCZcIqM93tGRa4XADxToXp2tpcqiKwQGtVe/2fOVcl6sg=
