travis:
  secure:
    BINSTAR_TOKEN: ShcIIOVS9eKkPq62ZZLxWB5LKepzwaKrkw0MKInUnTxGgXRw/jXj6mZ3WjHgtNnJAO4YScATqrZ9HS32sNa2dSRrkh18YmHToeeWHqduUEfgEw4rmdK1QpnnXupzX860CcgGiW/rR0bgiSpeMQiJOiYbuyFU68QjvQfDjfy5+8V4vuy/s5T/0OIWFVT0OwxMozkW/9LjbqM0j8MwqjcDmFkG49jNIb1wltTeR4266kZHYXZX5XsdrrcJD55mrpNUB1c/bys+hd/ySKGlaSQcrHL6NIlH8CR552dD8LXTA9FX2QWszgeQVVhJMhIROSYGdLhim4lEd1aNtuErFoCp5KSfeulT0uB8yP6nVnuW7MPnRGm1mthkwscJciLANCP5nUeiz2gF3oGHuoc9pNj74gp3tvZ/PpD4qWlyoP4UT7OpYNBZ3kFLkMZj+m+J8UQybNi0+4ckMzZ6EHydCZy4TEGnacyMAFNJ+2iKWfMoKOW9A8NdWMI+Rc7gAAIfw87NNW6/keclsdkb+Eb2SrXyxMqVe2ESpIAgLiA3FCsBZMIldCj95+YlfETvllYYpluTN8QJlVELNkmxGxhTO/zYaKnzxA9L/6dlP0i92bcjfsIz77PQeCPxYlGGU6ZCAuStRxl0pHSjnA/y2mMDtDfGftwSZEQXZDJ75UZ18r0FZJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
